export const departments = [
    { id: '1', name: 'Antioquia' },
    { id: '2', name: 'Cundinamarca' },
    { id: '3', name: 'Atlántico' },
    { id: '4', name: 'Bolívar' },
    { id: '5', name: 'Boyacá' },
    { id: '6', name: 'Caldas' },
    { id: '7', name: 'Caquetá' },
    { id: '8', name: 'Casanare' },
    { id: '9', name: 'Cauca' },
    { id: '10', name: 'Cesar' },
    { id: '11', name: 'Chocó' },
    { id: '12', name: 'Córdoba' },
    { id: '13', name: 'Guainía' },
    { id: '14', name: 'Guaviare' },
    { id: '15', name: 'Huila' },
    { id: '16', name: 'La Guajira' },
    { id: '17', name: 'Magdalena' },
    { id: '18', name: 'Meta' },
    { id: '19', name: 'Nariño' },
    { id: '20', name: 'Norte de Santander' },
    { id: '21', name: 'Putumayo' },
    { id: '22', name: 'Quindío' },
    { id: '23', name: 'Risaralda' },
    { id: '24', name: 'San Andrés y Providencia' },
    { id: '25', name: 'Santander' },
    { id: '26', name: 'Sucre' },
    { id: '27', name: 'Tolima' },
    { id: '28', name: 'Valle del Cauca' },
    { id: '29', name: 'Vaupés' },
    { id: '30', name: 'Vichada' },
];

export const cities = {
    '1': ['Medellín', 'Envigado', 'Itagüí', 'Bello', 'Rionegro'],
    '2': ['Bogotá', 'Soacha', 'Zipaquirá', 'Facatativá', 'Chía'],
    '3': ['Barranquilla', 'Soledad', 'Malambo', 'Puerto Colombia', 'Galapa'],
    '4': ['Cartagena', 'Magangué', 'Turbaco', 'Arjona', 'El Carmen de Bolívar'],
    '5': ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Puerto Boyacá'],
    '6': ['Manizales', 'Villamaría', 'Chinchiná', 'La Dorada', 'Riosucio'],
    '7': ['Florencia', 'San Vicente del Caguán', 'Puerto Rico', 'Cartagena del Chairá', 'El Doncello'],
    '8': ['Yopal', 'Aguazul', 'Villanueva', 'Monterrey', 'Tauramena'],
    '9': ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Piendamó', 'Patía'],
    '10': ['Valledupar', 'Aguachica', 'Bosconia', 'Codazzi', 'Curumaní'],
    '11': ['Quibdó', 'Istmina', 'Tadó', 'Condoto', 'Bahía Solano'],
    '12': ['Montería', 'Lorica', 'Sahagún', 'Cereté', 'Montelíbano'],
    '13': ['Inírida', 'Puerto Colombia', 'La Guadalupe', 'San Felipe', 'Cacahual'],
    '14': ['San José del Guaviare', 'El Retorno', 'Miraflores', 'Calamar', 'Chirajara'],
    '15': ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre'],
    '16': ['Riohacha', 'Maicao', 'Uribia', 'Fonseca', 'San Juan del Cesar'],
    '17': ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Aracataca'],
    '18': ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'San Martín'],
    '19': ['Pasto', 'Tumaco', 'Ipiales', 'Túquerres', 'La Unión'],
    '20': ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario', 'Los Patios'],
    '21': ['Mocoa', 'Puerto Asís', 'Sibundoy', 'Orito', 'La Hormiga'],
    '22': ['Armenia', 'Calarcá', 'Montenegro', 'La Tebaida', 'Quimbaya'],
    '23': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Belén de Umbría'],
    '24': ['San Andrés', 'Providencia', 'Santa Catalina'],
    '25': ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta', 'Barrancabermeja'],
    '26': ['Sincelejo', 'Corozal', 'Sampués', 'San Marcos', 'Tolú'],
    '27': ['Ibagué', 'Espinal', 'Honda', 'Melgar', 'Líbano'],
    '28': ['Cali', 'Palmira', 'Buenaventura', 'Tuluá', 'Cartago'],
    '29': ['Mitú', 'Carurú', 'Taraira', 'Pacoa', 'Yavaraté'],
    '30': ['Puerto Carreño', 'La Primavera', 'Cumaribo', 'Santa Rosalía', 'Morichal']
};
